### PR TITLE
Docs for logs

### PR DESCRIPTION
**Pull request by harjaapdhillon16**
Docs for logs added

### CODE REVIEW

**Review by Megha-Dev-19 — APPROVED** [review]
LGTM, but can we also wait for @robert-zaremba approval

**Review by robert-zaremba — CHANGES_REQUESTED** [review]
1. I've update the docs a bit
2. added todo - please update it
3. Let's move this file to `docs/logs.md`

**Comment by harjaapdhillon16** [comment]
@robert-zaremba ADDED THE REQUIRED CHANGES

**Review by robert-zaremba — APPROVED** [review]
formatting was wrong, i've fixed it.

**Pull request merged**
