### PR TITLE
Test for Verification of Email and Phone No

### PR DESCRIPTION
**Pull request by Megha-Dev-19**

### CODE REVIEW

**Comment by harjaapdhillon16** [comment]
● Console

    console.error
      Warning: Invalid DOM property `for`. Did you mean `htmlFor`?
          at label
          at div
          at div
          at div
          at setShowStep (/Users/harjaapdhillon/Desktop/code/i-am-human-dapp/i-am-human-new/src/components/pages/home/applyCommunityVerify/verifyPhoneAndEmail.js:45:3)

      126 |
      127 |   test('throws error on incorrect email', async () => {
    > 128 |     const { getByLabelText, getByText } = render(
          |                                                 ^
      129 |       <VerifyPhoneAndEmail
      130 |         setShowStep={setShowStep}
      131 |         setTelegramData={setTelegramData}

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3749:9)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3803:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3827:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:9541:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9830:5)
      at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10950:3)
      at completeWork (node_modules/react-dom/cjs/react-dom.development.js:22193:17)
      at completeUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26593:16)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26568:5)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25738:74)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:46:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:161:26)
      at render (node_modules/@testing-library/react/dist/pure.js:247:10)
      at _callee5$ (src/__tests__/verifyPhoneAndEmail.test.js:128:49)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)

    console.error
      Warning: An update to VerifyPhoneAndEmail inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at setShowStep (/Users/harjaapdhillon/Desktop/code/i-am-human-dapp/i-am-human-new/src/components/pages/home/applyCommunityVerify/verifyPhoneAndEmail.js:45:3)

      115 |         email,
      116 |       });
    > 117 |       setEmailSent(true);
          |       ^
      118 |       setTelegramData({ phone: value, email });
      119 |       toast.success('Otp sent successfully');
      120 |     } catch {

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at dispatchSetState (node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at setEmailSent (src/components/pages/home/applyCommunityVerify/verifyPhoneAndEmail.js:117:7)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)

    console.error
      Warning: An update to VerifyPhoneAndEmail inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at setShowStep (/Users/harjaapdhillon/Desktop/code/i-am-human-dapp/i-am-human-new/src/components/pages/home/applyCommunityVerify/verifyPhoneAndEmail.js:45:3)

      121 |       toast.error('Otp sent failed');
      122 |     } finally {
    > 123 |       setLoading(false);
          |       ^
      124 |     }
      125 |   };
      126 |

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at dispatchSetState (node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at setLoading (src/components/pages/home/applyCommunityVerify/verifyPhoneAndEmail.js:123:7)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)


**THESE ARE ERRORS COMING UP IN CONSOLE WHILE RUNNING THE TEST COMMAND , PLEASE INSPECT AND FIX**

**Review by harjaapdhillon16 — CHANGES_REQUESTED** [review]
Please fix the console errors

**Comment by Megha-Dev-19** [comment]
> Please fix the console errors

Thanks for informing, I have fixed the errors

**Review by harjaapdhillon16 — APPROVED** [review]
looks good

**Pull request merged**
